create table livro (id bigint generated by default as identity, autor varchar(255), paginas integer, titulo varchar(255), primary key (id));

    create table livro (
       id int8 generated by default as identity,
        autor varchar(255),
        paginas int4,
        titulo varchar(255),
        primary key (id)
    );

    create table livro (
       id int8 generated by default as identity,
        autor varchar(255),
        paginas int4,
        titulo varchar(255),
        primary key (id)
    );
